### ISSUE TITLE
Questions regarding the point masses

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#11]
The documentation concerning the point masses is a bit confusing, and I'm a bit worried that I would be accidentally making wrong assumptions as the code currently stands. 

The docs say "Keep in mind that point masses are added automatically to the structure depending on the connectivity matrices." Here are a few questions to answer about this.

1. Is there any way to turn this assumption off entirely? Does that break the dynamics solver?

2. It seems this says "point masses are automatically placed where cables connect, but no bar is present," as if the point masses were suspended within a cable net (cable net = tensegrity without bars.) Does this happen often, is it a useful feature, or is it necessary due to the dynamics formulation?

**Comment by vaishnavtv** [comment]
There is presently no way for the user to turn off the point mass addition feature. We have chosen to incorporate attaching point masses because of our assumption of ideal, massless strings. 
If we consider the case of a cable net without any point masses, the structure itself would be entirely massless, which would not facilitate any dynamic analysis of such a system.

**Comment by apsabelhaus** [comment]
That makes sense, good reasoning. Would it be possible to describe this somewhere? Maybe in the User Guide, or somewhere in the code itself?

**Comment by vaishnavtv** [comment]
Of course, I will make a note of it in the User Guide.
