### ISSUE TITLE
Comments about / errors in example: Template_DBar

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [uqLab/stedy#3]
About `Template_DBar.m`

1. When I run this example I receive a question on the command prompt `Enter output time-step:`, please can you add a suggested sensible time-step? E.g. rephrase it as `Enter output time-step (e.g. 1):`
2. After entering 1 as the output time-step I get the following error message:

 ```none
Error using animateTenseg (line 29)
The specified profile is not valid.

Error in Template_DBar (line 147)
animateTenseg(t,y,tData,time_loc,'DBar_Animation.mp4','MPEG-4',frameRate,AZ, EL,axLims);
```

I am using a 64-bit Ubuntu 18.04 machine with MATLAB R2018b.

**Comment by Kevin-Mattheus-Moerman** [comment]
I get the same error for other examples

**Comment by Kevin-Mattheus-Moerman** [comment]
Side note, if you want to avoid issues like this you could animate it in MATLAB directly (e.g. see the [`anim8`](https://github.com/gibbonCode/GIBBON/blob/master/docs/HELP_anim8.m) function in the [GIBBON](https://github.com/gibbonCode/GIBBON) toolbox I maintain).

**Comment by vaishnavtv** [comment]
Thank you @Kevin-Mattheus-Moerman, I'll make the suggested change to the output time-step prompt. 0.01 is usually chosen as the output time-step to ensure higher accuracy. 
It is generally recommended that the 'Refine' option be turned on in ODE options to avoid errors due to numerical extrapolation, but I see that the Template file itself doesn't have it included in the options. I'll make the change there and also edit the User Guide to reflect the prompt change. 

I'll also make the necessary changes as suggested about the VideoWriter format. Thank you for the GIBBON recommendation. I'll take a look.

**Comment by vaishnavtv** [comment]
Fixed. Added OS check to animateTenseg.m and updated prompt message for output time-step.

**Comment by Kevin-Mattheus-Moerman** [comment]
:+1:
