### ISSUE TITLE
Equilibrium solver undocumented

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#9]
The file tensegEq.m is very interesting, but the underlying procedure doesn't seem to be really documented, doesn't appear in the author's corresponding preprint, and isn't anything that I've seen before in the literature. 

I would suggest the following, so that users can verify why the equilibrium solver works as it does.

Equilibrium is a common problem in tensegrity structures (form-finding), and a great number of assumptions are made in tensegEq.m that need to be explained. Example – seems like a constraint satisfaction problem, no objective function, as opposed to an energy minimization problem. This code should be commented, and the approach should be compared to that of something such as the Tibert and Pellegrino paper “Review of Form-Finding Methods for Tensegrity Structures” from IJSS in 2003. 

In particular - papers such as Friesen's 2014 ICRA paper on the DuCTT robot propose a quadratic program to solve this problem, so it's worth saying why you're doing a linear program (constraint satisfaction) instead.

Also, should be made explicit that equilibrium is posed in terms of force-densities (and for what reasons – there are good ones just needs explanation) and how those then become equilibrium inputs for the dynamics problem (e.g. how they’re transformed into forces, and maybe then into rest lengths?)

**Comment by addyhsu** [comment]
tensegEq.m is not a form-finding solver, but to find force densities of strings in an equilibrium condition where a structure is given. That means all nodes in the system are known before solving the unknown forces.

From eq 31 in our corresponding paper, we set \ddot{q} to be zero and others are all known except for \sigma, so it becomes a linear system. Since strings only sustain tension, \sigma should always be greater than zero. Therefore, given a minimum force for each node, one can easily determine the force densities \sigma. The reason to use linprog is that we need to deal with equilibrium conditions which are subject to lower bound of \sigma.

Once we solve for \sigma, we use the relationship in eq 25 of the paper to obtain rest length of the strings and save it as a parameter in tData. This value is what we use in the core code of the dynamics.

**Comment by apsabelhaus** [comment]
very welcome! again, nice work on this project. I really am very interested in this equilibrium solution.

**Comment by vaishnavtv** [comment]
I have addressed this in the function help document in the Docs folder. Please let me know if the description is sufficient.
